# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dfc47824ca59dd7548db946febe3a1aba3e2d88a2a1f600ba0850d576645c9c656f56d67bf859e4fa9d3c5278ff1c08fa5cc5fb532c6e8816ed3c51bf2cf039f

test:
  secret_key_base: 864e6c3e6d3627591c46dc3026473b693795dc1c7ca11bc570357064fb0b2b4b67829c9a1bde1572cb7db4764f6ca513d45650bd63c1e460873c922df34aee44

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
